import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Grid, GridItem, Show } from "@chakra-ui/react";
import "./globals.css";
import { Providers } from "./providers";
import NavBar from "./NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Grid
            templateAreas={{
              base: `"nav" "main"`,
              lg: `"nav nav" "aside main"`,
            }}
          >
            <GridItem area="nav">
              <NavBar />
            </GridItem>
            <GridItem
              area="aside"
              bg="gold"
              display={{ base: "none", lg: "block" }}
            >
              Aside
            </GridItem>

            <GridItem area="main" bg="dodgerblue">
              {children}
            </GridItem>
          </Grid>
        </Providers>
      </body>
    </html>
  );
}
